# File: .github/workflows/repo-sync.yml
name: All_Scripts-ğŸ”„è‡ªåŠ¨åŒæ­¥ğŸ”„
on:
  schedule:
    - cron: '20 9 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: repo-sync
jobs:
  repo-sync:
    env:
      PAT: ${{ github.event.client_payload.PAT || secrets.PAT }} #æ­¤å¤„PATéœ€è¦ç”³è¯·ï¼Œæ•™ç¨‹è¯¦è§ï¼šhttps://www.jianshu.com/p/bb82b3ad1d11
      dst_key: ${{ secrets.GITEE_PRIVATE_KEY }} # æˆ‘è‡ªå·±åŒæ­¥åˆ°giteeä½¿ç”¨ï¼Œå…¶ä»–äººå¯å¿½ç•¥
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: feizao-ğŸ”„è‡ªåŠ¨åŒæ­¥ğŸ”„
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/age174/-.git"
          source_branch: "main"
          destination_branch: "feizao"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}
      - name: ziye-ğŸ”„è‡ªåŠ¨åŒæ­¥ğŸ”„
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/6Svip120apk69/gitee_q8qsTAUA_cThxc1RBVUE.git"
          source_branch: "main"
          destination_branch: "ziye"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}
      - name: ZhiYi-N-ğŸ”„è‡ªåŠ¨åŒæ­¥ğŸ”„
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/ZhiYi-N/Private-Script.git"
          source_branch: "master"
          destination_branch: "ZhiYi-N"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}
      - name: CenBoMin-ğŸ”„è‡ªåŠ¨åŒæ­¥ğŸ”„
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/CenBoMin/GithubSync.git"
          source_branch: "main"
          destination_branch: "CenBoMin"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}
      - name: Sunert-ğŸ”„è‡ªåŠ¨åŒæ­¥ğŸ”„
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/Sunert/Scripts.git"
          source_branch: "master"
          destination_branch: "Sunert"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}
      - name: caixukun-ğŸ”„è‡ªåŠ¨åŒæ­¥ğŸ”„
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/caixukun112/js.git"
          source_branch: "master"
          destination_branch: "caixukun"
          github_token: ${{ github.event.client_payload.PAT || secrets.PAT }}
